notes: "This dataset contains standardised Humanitarian Needs Overview data taken from the OCHA HPC system."
license_id: "cc-by-igo"
methodology: "Registry"
dataset_source: "Humanitarian Partners"
caveats: ""
private: False  # has to be True or False
